---
title: "Processing evaluation RMassBank"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir= "C:/Daten/Michele/20181031 MassBank March")
```

## Summary for each cpd

```{r libraries}


library(RMassBank)
library(plyr)
library(mzR)

```

## Including Plots

EIC with associated triggered MS/MS, per compound
```{r plots, echo=FALSE, results='asis'}
#test
w <- loadMsmsWorkspace("results/spectra-pH-processed.RData")

for(i in seq_along(w@spectra))
{
  cpd <- w@spectra[[i]]
  found <- ifelse(cpd@found, "(OK)", "(not found)")
  cat(paste('\n\n##', cpd@id, cpd@name,'\n', 'mz =', round(cpd@mz, 4), found, "\n\n"))
  
  if(length(cpd@children) > 0)
  {
    par(mfrow=c(4,3))
    par(mar=c(3,2,0,1)+0.1)
    par(oma=c(0,0,0,0)+0.1)
    par(xaxs='i')
    mzrange <- range(laply(cpd@children, function(sp) range(sp@mz)))
    for(i in seq_along(cpd@children))
    {
      sp <- cpd@children[[i]]
      spData <- getData(sp)
      plot.new()
      plot.window(xlim=mzrange, ylim=range(0, spData$intensity))
      axis(1)
      box(bty='l')
      lines(intensity ~ mz, spData, type='h', xlim=mzrange)
      lines(intensity  ~ mz, spData[spData$good,,drop=FALSE], col='red', lwd=1, type='h')
      legend('topleft', legend=format(max(spData$intensity), scientific = TRUE, digits=2), bty = 'n')
    }
  }
  

}

```

